-- MySQL Script generated by MySQL Workbench
-- Wed Apr 16 11:20:30 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Zákazníci`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Zákazníci` (
  `idZákazníci` INT NOT NULL,
  `Jméno zákazníka` VARCHAR(45) NOT NULL,
  `Počet návštěv` INT NOT NULL,
  `Telefon` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Nabídky_idNabídky` INT NOT NULL,
  `Příjmení Zákazníka` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idZákazníci`),
  UNIQUE INDEX `Jméno zákazníka_UNIQUE` (`Jméno zákazníka` ASC) VISIBLE,
  UNIQUE INDEX `idZákazníci_UNIQUE` (`idZákazníci` ASC) VISIBLE,
  UNIQUE INDEX `telefon_UNIQUE` (`Telefon` ASC) VISIBLE,
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Správci`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Správci` (
  `idSprávci` INT NOT NULL,
  `JmenoSpravce` VARCHAR(45) NOT NULL,
  `PijmeniSpravce` VARCHAR(45) NOT NULL,
  `Vek` INT NOT NULL,
  `dobaZaměstnání` VARCHAR(45) NULL,
  `Správcicol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSprávci`),
  UNIQUE INDEX `idSprávci_UNIQUE` (`idSprávci` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Lokace`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Lokace` (
  `idLokace` INT NOT NULL,
  `Nazev` VARCHAR(45) NOT NULL,
  `Mesto` VARCHAR(45) NOT NULL,
  `Ulice` VARCHAR(45) NOT NULL,
  `Správci_idSprávci` INT NOT NULL,
  PRIMARY KEY (`idLokace`),
  UNIQUE INDEX `idLokace_UNIQUE` (`idLokace` ASC) VISIBLE,
  UNIQUE INDEX `Nazev_UNIQUE` (`Nazev` ASC) VISIBLE,
  INDEX `fk_Lokace_Správci1_idx` (`Správci_idSprávci` ASC) VISIBLE,
  CONSTRAINT `fk_Lokace_Správci1`
    FOREIGN KEY (`Správci_idSprávci`)
    REFERENCES `mydb`.`Správci` (`idSprávci`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Herci`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Herci` (
  `idHerci` INT NOT NULL,
  `JmenoHerce` VARCHAR(45) NOT NULL,
  `Role` VARCHAR(45) NOT NULL,
  `Příjmení Herce` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idHerci`),
  UNIQUE INDEX `idHerci_UNIQUE` (`idHerci` ASC) VISIBLE,
  UNIQUE INDEX `JmenoHerce_UNIQUE` (`JmenoHerce` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EscapeRoom`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EscapeRoom` (
  `idEscapeRoom` INT NOT NULL,
  `Lokace_idLokace` INT NOT NULL,
  `Obtížnost` VARCHAR(45) NOT NULL,
  `Strašidelnost` VARCHAR(45) NOT NULL,
  `Cena` DECIMAL NOT NULL,
  `Doporučený věk` VARCHAR(45) NOT NULL,
  `Téma` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEscapeRoom`),
  UNIQUE INDEX `idEscapeRoom_UNIQUE` (`idEscapeRoom` ASC) VISIBLE,
  INDEX `fk_EscapeRoom_Lokace1_idx` (`Lokace_idLokace` ASC) VISIBLE,
  UNIQUE INDEX `Téma_UNIQUE` (`Téma` ASC) VISIBLE,
  CONSTRAINT `fk_EscapeRoom_Lokace1`
    FOREIGN KEY (`Lokace_idLokace`)
    REFERENCES `mydb`.`Lokace` (`idLokace`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rezervace`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rezervace` (
  `idRezervace` INT NOT NULL,
  `DatumRezervace` DATE NOT NULL,
  `ČasRezervace` TIME NOT NULL,
  `EscapeRoom_idEscapeRoom` INT NOT NULL,
  `Zákazníci_idZákazníci` INT NOT NULL,
  PRIMARY KEY (`idRezervace`),
  UNIQUE INDEX `idtable1_UNIQUE` (`idRezervace` ASC) VISIBLE,
  INDEX `fk_Rezervace_EscapeRoom1_idx` (`EscapeRoom_idEscapeRoom` ASC) VISIBLE,
  INDEX `fk_Rezervace_Zákazníci1_idx` (`Zákazníci_idZákazníci` ASC) VISIBLE,
  CONSTRAINT `fk_Rezervace_EscapeRoom1`
    FOREIGN KEY (`EscapeRoom_idEscapeRoom`)
    REFERENCES `mydb`.`EscapeRoom` (`idEscapeRoom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rezervace_Zákazníci1`
    FOREIGN KEY (`Zákazníci_idZákazníci`)
    REFERENCES `mydb`.`Zákazníci` (`idZákazníci`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`recenze`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`recenze` (
  `idrecenze` INT NOT NULL,
  `datum` DATE NOT NULL,
  `autor` VARCHAR(45) NOT NULL,
  `Obsah` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idrecenze`),
  UNIQUE INDEX `idrecenze_UNIQUE` (`idrecenze` ASC) VISIBLE,
  UNIQUE INDEX `autor_UNIQUE` (`autor` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Herci_has_recenze`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Herci_has_recenze` (
  `Herci_idHerci` INT NOT NULL,
  `recenze_idrecenze` INT NOT NULL,
  PRIMARY KEY (`Herci_idHerci`, `recenze_idrecenze`),
  INDEX `fk_Herci_has_recenze_recenze1_idx` (`recenze_idrecenze` ASC) VISIBLE,
  INDEX `fk_Herci_has_recenze_Herci1_idx` (`Herci_idHerci` ASC) VISIBLE,
  CONSTRAINT `fk_Herci_has_recenze_Herci1`
    FOREIGN KEY (`Herci_idHerci`)
    REFERENCES `mydb`.`Herci` (`idHerci`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Herci_has_recenze_recenze1`
    FOREIGN KEY (`recenze_idrecenze`)
    REFERENCES `mydb`.`recenze` (`idrecenze`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`recenze_has_EscapeRoom`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`recenze_has_EscapeRoom` (
  `recenze_idrecenze` INT NOT NULL,
  `EscapeRoom_idEscapeRoom` INT NOT NULL,
  PRIMARY KEY (`recenze_idrecenze`, `EscapeRoom_idEscapeRoom`),
  INDEX `fk_recenze_has_EscapeRoom_EscapeRoom1_idx` (`EscapeRoom_idEscapeRoom` ASC) VISIBLE,
  INDEX `fk_recenze_has_EscapeRoom_recenze1_idx` (`recenze_idrecenze` ASC) VISIBLE,
  CONSTRAINT `fk_recenze_has_EscapeRoom_recenze1`
    FOREIGN KEY (`recenze_idrecenze`)
    REFERENCES `mydb`.`recenze` (`idrecenze`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recenze_has_EscapeRoom_EscapeRoom1`
    FOREIGN KEY (`EscapeRoom_idEscapeRoom`)
    REFERENCES `mydb`.`EscapeRoom` (`idEscapeRoom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Herci_has_EscapeRoom`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Herci_has_EscapeRoom` (
  `Herci_idHerci` INT NOT NULL,
  `EscapeRoom_idEscapeRoom` INT NOT NULL,
  PRIMARY KEY (`Herci_idHerci`, `EscapeRoom_idEscapeRoom`),
  INDEX `fk_Herci_has_EscapeRoom_EscapeRoom1_idx` (`EscapeRoom_idEscapeRoom` ASC) VISIBLE,
  INDEX `fk_Herci_has_EscapeRoom_Herci1_idx` (`Herci_idHerci` ASC) VISIBLE,
  CONSTRAINT `fk_Herci_has_EscapeRoom_Herci1`
    FOREIGN KEY (`Herci_idHerci`)
    REFERENCES `mydb`.`Herci` (`idHerci`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Herci_has_EscapeRoom_EscapeRoom1`
    FOREIGN KEY (`EscapeRoom_idEscapeRoom`)
    REFERENCES `mydb`.`EscapeRoom` (`idEscapeRoom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
